language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
install:
- wget http://www.biicode.com/downloads/latest/ubuntu32
- mv ubuntu32 bii-ubuntu32.deb
- (! sudo dpkg -i bii-ubuntu32.deb ) && sudo apt-get -f install
- rm bii-ubuntu32.deb
- wget http://www.cmake.org/files/v3.0/cmake-3.0.1-Linux-i386.tar.gz
- tar -xzf cmake-3.0.1-Linux-i386.tar.gz
- sudo cp -fR cmake-3.0.1-Linux-i386/* /usr
- rm -rf cmake-3.0.1-Linux-i386
- rm cmake-3.0.1-Linux-i386.tar.gz
script:
- cmake --version
- bii init biicode_project
- mkdir -p ./biicode_project/blocks/eigen/eigen
- mv !(biicode_project) ./biicode_project/blocks/eigen/eigen
- cd biicode_project
- bii find -um
- bii cpp:build
- ./bin/eigen_eigen_failtest_failtest_sanity_check && ls ./bin/eigen_eigen_failtest_failtest_sanity_check
after_success:
- bii user eigen -p $BII_EIGEN_PASSWORD
- bii publish
env:
  global:
    secure: Gayj0Eyxvx2hjKFE7qcuIEK2pyioYckJ2+Kkwzn+hOvj3griBdlHOvTCsHpa+2qQXx4zE64wdw97vLCzv3mY/rmcB2MpbSmz3Sy6WCHXjCpYypRhoA/9tO3gk26aBQ9b8j7dDuiOmIG1AfWHsKhMGCqhdpvIwxnBAZ3jOGCf1mU=
